# Description of Scipy

* SciPy is an open-source Python library
* Enables us to manipulate and visualise data using a variety of high-level commands
  Mathematics, scientific computing, engineering, and technical computing.
* SciPy is designed to work with NumPy arrays. 
* It includes many user-friendly and efficient numerical routines, such as numerical     integration and optimization routines. 

### Why Scipy
 * SciPy has a number of sub-packages that help with the most common problems in Scientific Computation. 
 * It's easy to use and understand, and it has a fast computational power.
 * It can operate on an array of NumPy library.

# Linear Algebra with SciPy

## Installation 

#### pip install scipy 
#### &
#### conda install -c anaconda scipy   #for anaconda

## Scipy has Special Function Package
* scipy.special package contains numerous functions of mathematical physics.
* SciPy special function includes Cubic Root, Exponential, Log sum Exponential, Lambert, Permutation and Combinations, Gamma, Bessel, hypergeometric, Kelvin, beta, parabolic cylinder, Relative Error Exponential, etc.

# Permutation 
A permutation is a mathematical approach used to calculate the number of possible arrangements in a set when the order of the arrangements is important

## Application of Permutation 
* Arranging people
* Arranging digits 
* Arranging numbers
* Arranging alphabets,letters 
* Arranging colours

In [6]:
# We see one example of Permutation
from scipy.special import perm
per = perm(4, 2,  True)   # exact = False we get values in float
print(per)

12


# Combination
A combination is a mathematical technique that determines the number of possible arrangements in a collection of items where the order of the selection does not matter

## Application of Combination
- Selection of menu 
* Selection of food 
* Selection of clothes 
* Selection of subjects 

In [7]:
from scipy.special import comb
per = comb(5, 2, exact = False)   
print(per)

10.0


# Linear Equation
### Linear Equation 3x + 2y + 0z = 2, x - y + 0z = 4, 0x + 5y + z = -1

### Real Life Applications of Linear Equations
* Expressing the word problem as a mathematical statement (algebraic expression).
* These linear equations can then be solved using various problem solving methods to determine the value of the unknown variables.

In [8]:
#importing the scipy and numpy packages
from scipy import linalg
import numpy as np

#Declaring the numpy arrays
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

#Passing the values to the solve function
x = linalg.solve(a, b)

#printing the result array
print(x)

[ 2. -2.  9.]


### Finding Determinant 


In [9]:
from scipy import linalg
import numpy as np
two_d_array = np.array([ [4,4], [1,6] ])  #define square matrix
linalg.det( two_d_array )   #pass values to det() function

20.0

### Inverse Matrix 
#### Syntax – scipy.linalg.inv()
 Inverse Matrix of Scipy calculates the inverse of any square matrix.

In [10]:
from scipy import linalg
import numpy as np
# define square matrix
two_d_array = np.array([ [4,4], [1,6] ])
two_d_array
#pass value to function inv()
linalg.inv( two_d_array )

array([[ 0.3 , -0.2 ],
       [-0.05,  0.2 ]])

## Integration

'''The general form of quad is scipy.integrate.quad(f, a, b), Where ‘f’ is the name of the function to be integrated. 
Whereas, ‘a’ and ‘b’ are the lower and upper limits, respectively.'''

### Real Life Applications of Integration
* Predict the position of planets
* To calculate the Centre of Mass, 
* Centre of Gravity and Mass Moment of Inertia of a sports utility vehicle.

In [11]:
import scipy.integrate
from numpy import exp
f= lambda x:exp(-x**2)
i = scipy.integrate.quad(f, 0, 1)
print(i)

(0.7468241328124271, 8.291413475940725e-15)


## Derivative

### Why we use derivatives
* They are used to locate the maxima and minima of functions and indicate slope 
* This is beneficial in terms of optimization

### Application of Derivatives in Real Life
* To calculate the profit and loss in business using graphs.
* To determine the speed or distance covered such as miles per hour, kilometre per hour etc.
* Derivatives are used to derive many equations in Physics.
* To check the temperature variation.
* In the study of Seismology like to find the range of magnitudes of the earthquake.

In [12]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
derivative(f, 1.0, dx=1e-6)

4.999999999921734

## Eigenvalues and Eigenvector
#### syntax – scipy.linalg.eig()
* eigenvalue states that how much variance there is in the data in that direction, i.e how spread out the data is on the line
 

### Some uses of Eigenvalues and Eigenvectors
* Using singular value decomposition for image compression
* Deriving Special Relativity is more natural in the language of linear algebra
* Spectral Clustering
* Dimensionality Reduction/PCA

In [13]:
# Now lets we find the Eigenvalue of (X) and correspond eigenvector of a two-dimensional square matrix.
from scipy import linalg
import numpy as np

#define two dimensional array
arr = np.array([[4,4],[6,2]])

#pass value into function
eg_val, eg_vect = linalg.eig(arr)

#get eigenvalues
print('Eigenvalues:',eg_val)

#get eigenvectors
print('Eigenvector:',eg_vect)

Eigenvalues: [ 8.+0.j -2.+0.j]
Eigenvector: [[ 0.70710678 -0.5547002 ]
 [ 0.70710678  0.83205029]]


# Sparse Matrix
### What is the use of sparse matrix
* Storage: There are less number of non-zero elements than zeros, less memory may be needed to store them.
* Computing time: Computing time can be saved by logically designing a data structure that traverses (Zig-zag path) only non-zero elements.

In [14]:
# import necessary modules 
from scipy import sparse 
from scipy.sparse import linalg 
# Row-based linked list sparse matrix 
A = sparse.lil_matrix((1000, 1000)) 
A[0,:100] = np.random.rand(100) 
A[1,100:200] = A[0,:100] 
A.setdiag(np.random.rand(1000)) 
#print(A) 

# Convert this matrix to Compressed Sparse Row format. 
A.tocsr()    #Return a copy of this matrix in Compressed Sparse Row format Duplicate entries will be summed together.
  
A = A.tocsr() 
b = np.random.rand(1000) 
c = linalg.spsolve(A, b) 
# it will print ans array of 1000 size 
c[0:10] # there are 1000 values but we will print only few of them

array([-2.17152358e+03, -1.96589955e+02,  1.90915675e-01,  1.26046481e+00,
        1.25297933e+02,  1.17977628e+00,  4.02911549e-01,  1.01961985e+01,
        7.33678432e-01,  6.46314352e-01])